### ISSUE TITLE
Does not work for me on Windows 10

### ISSUE THREAD

**Issue by PhilAndrew** [lloydmeta/scala-akka-cv-part1#1]
Hi there, I'm on Windows 10.

Try your code and for me this happens.

```

C:\home\projects\scala-akka-cv-part1-master>activator run
[info] Loading project definition from C:\home\projects\scala-akka-cv-part1-mast
er\project
[info] Set current project to scala-cv-part1 (in build file:/C:/home/projects/sc
ala-akka-cv-part1-master/)
[info] Running com.beachape.WebcamWindow
[info] [ERROR] [03/15/2016 11:48:18.448] [default-akka.actor.default-dispatcher-
4] [akka://default/user/$a] cvRetrieveFrame() Error: Could not retrieve frame. (
Has start() been called?)
[info] org.bytedeco.javacv.FrameGrabber$Exception: cvRetrieveFrame() Error: Coul
d not retrieve frame. (Has start() been called?)
[info]  at org.bytedeco.javacv.OpenCVFrameGrabber.grab(OpenCVFrameGrabber.java:2
39)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.graphFrame(Webcam.scal
a:108)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.com$beachape$video$Web
cam$WebcamFramePublisher$$emitFrames(Webcam.scala:100)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher$$anonfun$receive$1.app
lyOrElse(Webcam.scala:89)
[info]  at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.akka$stream$actor$Acto
rPublisher$$super$aroundReceive(Webcam.scala:69)
[info]  at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.s
cala:270)
[info]  at com.beachape.video.Webcam$WebcamFramePublisher.aroundReceive(Webcam.s
cala:69)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:397)
[info]  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
[info]  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
[info]  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)
[info]
Terminate batch job (Y/N)?
```

Also I made some code which does work for me on my Windows 10, but this code is not using the Akka, just using webcam.
https://github.com/PhilAndrew/ScalaOpenCVCameraWhichWorks

Also I tried to enumerate cameras from your code, pasted into your code as follows but this doesn't work either.

```

  val cameraInformation = ""
  val n = org.bytedeco.javacv.OpenCVFrameGrabber.getDeviceDescriptions
  for (i <- 0 until n.length) {
    val info = n(i)
    println("Your information for camera:" + info + " and device index is=" + i)
  }

[error] Exception in thread "main" java.lang.UnsupportedOperationException: Devi
ce enumeration not support by OpenCV.
[error]         at org.bytedeco.javacv.OpenCVFrameGrabber.getDeviceDescriptions(
OpenCVFrameGrabber.java:39)
[error]         at com.beachape.WebcamWindow$.delayedEndpoint$com$beachape$Webca
mWindow$1(WebcamWindow.scala:15)
[error]         at com.beachape.WebcamWindow$delayedInit$body.apply(WebcamWindow
.scala:10)
[error]         at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction
```

Oh anyway this device enumeration doesn't work in my code either so thats not useful.

My webcam is a SJ4000 SJCAM USB.

**Comment by lloydmeta** [comment]
Hi,

Thanks for your feedback; I'm sorry to hear that it doesn't work for you on Windows (10, but maybe not limited to 10). The first error is concerning, because it says that `.start()` might not have been called which is impossible since it is called [here](https://github.com/lloydmeta/scala-akka-cv-part1/blob/master/src/main/scala/com/beachape/video/Webcam.scala#L62), so the error is likely a red herring for something else that has gone wrong in a totally unexpected manner.

I'm glad to see you got your own version working, but it looks like your project is completely different from this project, which makes it hard to pin down where things went haywire. In particular, it seems like you've changed the project definition (you aren't using the `sbt-opencv` plugin) _and_ the application code (as you mentioned, not using Akka).

Is it possible for you to try either one of the following and report back?
1. Use your project definition (not using `sbt-opencv`) in this project and see if the application works? If so, this likely means `sbt-opencv` isn't pulling in dependencies properly on your OS.
2. Use the `sbt-opencv` plugin in your project definition (instead of your own code) and see if it still works? If so, this likely means that the application code in this project somehow isn't compatible with your OS.

Since I don't have access to Windows, I would really appreciate your help in narrowing down the problem.

Thanks!

**Comment by lloydmeta** [comment]
Oh, one more thing, in a project that uses the  `sbt-opencv` plugin (e.g. the unmodified version of this project), can you run `inspect javaCppPlatform` in your SBT console and let me know what it shows? For example:

``` scala
> inspect javaCppPlatform
[info] Setting: java.lang.String = macosx-x86_64
[info] Description:
[info]  The platform that you want to compile for (defaults to the platform of the current computer). You can also set this via the "sbt.javacpp.platform" System Property 
[info] Provided by:
[info]  {file:/Users/Lloyd/Documents/scala_dev/scala-cv-part1/}scala-cv-part1/*:javaCppPlatform
[info] Defined at:
[info]  (com.beachape.sbt.javacpp.Plugin) Plugin.scala:14
[info] Reverse dependencies:
[info]  *:libraryDependencies
[info] Delegates:
[info]  *:javaCppPlatform
[info]  {.}/*:javaCppPlatform
[info]  */*:javaCppPlatform
```

**Comment by PhilAndrew** [comment]
Yes I will spend time on this tomorrow, I want to use your code to fetch data from the webcam.

**Comment by PhilAndrew** [comment]
My example is working now (wrong colors but OK BGR wrong) after exploring different options and it now uses your JavaCV plugin.

https://github.com/PhilAndrew/ScalaOpenCVCameraWhichWorks

Firstly a simple upgrade to OpenCV 3 didn't work as shown here in this branch.

https://github.com/PhilAndrew/ScalaOpenCVCameraWhichWorks/tree/opencv3

So also using your plugin also didn't work as well with that branches code...

I found code from here which works with OpenCV 3 http://answers.opencv.org/question/46638/java-how-capture-webcam-and-show-it-in-a-jpanel-like-imshow/

Then I integrated that in to master branch.

In answer to your question, 

```
> inspect javaCppPlatform
[info] Setting: java.lang.String = windows-x86_64
[info] Description:
[info]  The platform that you want to compile for (defaults to the platform of t
he current computer). You can also set this via the "sbt.javacpp.platform" Syste
m Property
[info] Provided by:
[info]  {file:/C:/home/projects/blog-scala-javacv-master/}blog-scala-javacv-mast
er/*:javaCppPlatform
[info] Defined at:
[info]  (com.beachape.sbt.javacpp.Plugin) Plugin.scala:14
[info] Reverse dependencies:
[info]  *:libraryDependencies
[info] Delegates:
[info]  *:javaCppPlatform
[info]  {.}/*:javaCppPlatform
[info]  */*:javaCppPlatform
>
```

So from the above I don't see any problem with your OpenCV sbt plugin. I have some working code as shown in master branch using your OpenCV sbt plugin. The next step which I have not done is to adapt your Akka project to work as in the same way as my project.

I will try to adapt your Akka code tomorrow as its getting late here. Maybe this indicates a bug in JavaCV for OpenCV 3 using the API your using to fetch video data.

**Comment by lloydmeta** [comment]
@PhilAndrew thanks for reporting back. This is interesting; you definitely seem to be on to something [here](https://github.com/PhilAndrew/ScalaOpenCVCameraWhichWorks/blob/master/src/main/scala/com/chimpler/javacv/FaceWebcamDetectorApp.scala#L50).

I found [this SO question](http://stackoverflow.com/questions/32237259/opencvframegrabber-javacv-in-matlab-doesnt-work) which suggested that for cross-platform purposes, it may be best to use `FrameGrabber.createDefault(0)` instead, so I've updated the code in this project to use that as well. Maybe it will work for you now as well?

**Comment by PhilAndrew** [comment]
Tried your suggestion of createDefault(0), did not work.

Here is a version of your project which works with val g = new VideoCapture(0) which means it works on my windows 10 machine.
https://github.com/PhilAndrew/scala-akka-cv-part1/tree/windows10

For me, that's good enough that it works it satisfy's my requirements for continuing on with my project, however it suggests there is a bug in JavaCV or OpenCV or just the Windows version of either as your code should work fine on Windows 10. I'll file a bug on JavaCV when get time.

For example, this person is trying code which looks like yours and says it doesn't work which may be the same bug.

http://stackoverflow.com/questions/26104756/javacv-opencvframegrabber-doesnt-start

Thanks for making the OpenCV sbt plugin, so useful.

If anyone else who reads this and is using Windows and has the same problem please add comments?

**Comment by lloydmeta** [comment]
@PhilAndrew interesting find! Also, thanks for filling the bug on JavaCV; I've promptly subscribed to that issue.

**Comment by lloydmeta** [comment]
@PhilAndrew from the other discussion, it looks like there is a regression on the JavaCV side of things that prevents OpenCVFrameGrabber from working, but for now, I've added `videoinput` as a preset to be included by default, which should allow FrameGrabber.createDefault to work; the latest version of `sbt-opencv` will have it included, and the latest version of this project uses that, so hopefully it will now run on your machine.

**Comment by PhilAndrew** [comment]
Great! I git clone'ed your code and it works now. Solved the problem and it displays the webcam without problem, good work.

```
[info] Done updating.
[info] Compiling 5 Scala sources to C:\home\projects\git\scala-akka-cv-part1\tar
get\scala-2.11\classes...
[info] Running com.beachape.WebcamWindow
[info]
[info] VIDEOINPUT SPY MODE!
[info]
[info] SETUP: Looking For Capture Devices
[info] SETUP: 0) J1455
[info] SETUP: 1 Device(s) found
[info]
[info]
[info] ***** VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****
[info]
[info] SETUP: Setting up device 0
[info] SETUP: J1455
[info] SETUP: Couldn't find preview pin using SmartTee
[info] SETUP: Default Format is set to 1280 by 720
[info] SETUP: trying requested format RGB24 @ 640 by 480
[info] SETUP: trying format RGB24 @ 640 by 480
[info] SETUP: trying format RGB32 @ 640 by 480
[info] SETUP: trying format RGB555 @ 640 by 480
[info] SETUP: trying format RGB565 @ 640 by 480
[info] SETUP: trying format YUY2 @ 640 by 480
[info] SETUP: trying format YVYU @ 640 by 480
[info] SETUP: trying format YUYV @ 640 by 480
[info] SETUP: trying format IYUV @ 640 by 480
[info] SETUP: trying format UYVY @ 640 by 480
[info] SETUP: trying format YV12 @ 640 by 480
[info] SETUP: trying format YVU9 @ 640 by 480
[info] SETUP: trying format Y411 @ 640 by 480
[info] SETUP: trying format Y41P @ 640 by 480
[info] SETUP: trying format Y211 @ 640 by 480
[info] SETUP: trying format AYUV @ 640 by 480
[info] SETUP: trying format Y800 @ 640 by 480
[info] SETUP: trying format Y8 @ 640 by 480
[info] SETUP: trying format GREY @ 640 by 480
[info] SETUP: trying format OTHER @ 640 by 480
[info] SETUP: Capture callback set
[info] SETUP: Device is setup and ready to capture.
[info]
[success] Total time: 18 s, completed Mar 19, 2016 9:39:06 AM

c:\home\projects\git\scala-akka-cv-part1>
```
